myShop/apps/orderApp/urls.py
from django.urls import path
from .views import *
#------------------------------------------------------------------------------


app_name='orders'

urlpatterns = [
    path('',shopCartView.as_view(),name='ordersmain'),
    path('show_shop_cart/',show_shop_cart,name='show_shop_cart'),
    path('add_to_shop_cart/',add_to_shop_cart,name='add_to_shop_cart'),
    path('delete_from_shop_cart/',delete_from_shop_cart,name='delete_from_shop_cart'),
    path('update_shop_cart/',update_shop_cart,name='update_shop_cart'),
    path('status_of_shop_cart/',status_of_shop_cart,name='status_of_shop_cart'),
    path('create_ordere/',CreateOrderView.as_view(),name='createorder'),
    path('checkout/<int:order_id>/',CheckoutOrderView.as_view(),name='checkout_order'),
    path('apply_coupon/<int:order_id>/',ApplyCoupon.as_view(),name='apply_coupon'),
]

myShop/myShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('accounts/',include('apps.accountsApp.urls',namespace='accounts')),
    path('product/',include('apps.productApp.urls',namespace='products')),
    path('order/',include('apps.orderApp.urls',namespace='orders')),
    path('discount/',include('apps.discountsApp.urls',namespace='discounts')),
    path('payments/',include('apps.paymentApp.urls',namespace='payments')),
    path('warehouse/',include('apps.warehouseApp.urls',namespace='warehouse')),
    path('search/',include('apps.searchApp.urls',namespace='search_app')),
    path('csw/',include('apps.comments_scoring_whislistApp.urls',namespace='csws')),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

myShop/apps/orderApp/models.py
from django.db import models
from apps.accountsApp.models import Customer
from apps.productApp.models import Product
from django.utils import timezone
import uuid
import utils
#------------------------------------------------------------------------------

class Payment(models.Model):
    payment_title = models.CharField(max_length=50,verbose_name='نوع پرداخت')

    def __str__(self):
        return self.payment_title

    class Meta:
        verbose_name ='پرداخت'
        verbose_name_plural ='روش پرداخت'
        db_table ='t_payment'   
#------------------------------------------------------------------------------

class OrderState(models.Model):
    order_state_title=models.CharField(max_length=100,verbose_name='وضعیت سفارش')

    def __str__(self):
        return self.order_state_title

    class Meta:
        verbose_name ='وضعیت سفارش'
        verbose_name_plural ='وضعیت سفارش ها' 
        db_table ='t_order_state'   


#------------------------------------------------------------------------------

class Order(models.Model):
    customer=models.ForeignKey(Customer,on_delete=models.CASCADE,related_name='orders',verbose_name='مشتری')
    register_date=models.DateField(default=timezone.now,verbose_name='تاریخ درج')
    update_date=models.DateField(auto_now=True,verbose_name='تاریخ ویرایش')
    is_finaly=models.BooleanField(default=False,verbose_name='وضعیت سفارش')
    order_code=models.UUIDField(unique=True,verbose_name='کد تولیدی برای سفارش',default=uuid.uuid4,editable=True)
    discount=models.IntegerField(default=0,verbose_name='تخفیف روی فاکتور',null=True,blank=True)
    description=models.TextField(null=True,blank=True,verbose_name='توضیحات')
    payment=models.ForeignKey(Payment,on_delete=models.CASCADE,related_name='payment_types',
                              null=True,blank=True,default=None,verbose_name='نوع پرداخت')
    order_state=models.ForeignKey(OrderState,on_delete=models.CASCADE,related_name='order_state',verbose_name='وضعیت سفارش',null=True,blank=True)
    
    
    def get_order_total_price(self):
        sum=0
        for item in self.orders_detail1.all():
            sum+=item.product.get_price_by_discount()*item.qty
        final_price,delivery,tax=utils.get_price_delivery_tax(sum,self.discount)    
        return int(final_price*10)    
            
            
    def __str__(self):
        return f'{self.customer}\t{self.id}\t{self.is_finaly}'

    class Meta:
        verbose_name ='سفارش'
        verbose_name_plural ='سفارشات'
        db_table ='t_order'    

#------------------------------------------------------------------------------

class OrderDetail(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='orders_detail1',verbose_name='سفارش')
    product=models.ForeignKey(Product,on_delete=models.CASCADE,related_name='orders_detail2',verbose_name='کالا')
    qty=models.PositiveIntegerField(default=1,verbose_name='تعداد')
    price=models.IntegerField(verbose_name='قیمت')

    def __str__(self):
        return f'{self.order}\t{self.product}\t{self.qty}\t{self.price}' 
     
    class Meta:
        verbose_name ='جزیئات سفارش'
        verbose_name_plural ='جزیئات سفارشات'
        db_table ='t_orderdetails'     
      
#------------------------------------------------------------------------------

myShop/apps/orderApp/forms.py
from django import forms
from .models import Payment

class OrderForm(forms.Form):
    name = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'نام'}),
        error_messages={'required':'این فیلد نمی تواند خالی باشد'}
    )
    family = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'نام خانوادگی'},),
        error_messages={'required':'این فیلد نمی تواند خالی باشد'}
    )
    email = forms.CharField(
        label='',
        widget=forms.EmailInput(attrs={'class': 'form-control','placeholder':'ایمیل'}),
        required=False
    )
    phone_number = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'class': 'form-control','placeholder':'شماره تلفن'}),
        required=False
    )
    address = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'آدرس','rows':'2'}),
        error_messages={'required':'این فیلد نمی تواند خالی باشد'}
    )
    description = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={'class': 'form-control','placeholder':'توضیحات','rows':'4'}),
        required=False
    )
    payment=forms.ChoiceField(
        label='',
        choices=[(item.pk,item) for item in Payment.objects.all()],
        widget=forms.RadioSelect()
    )

myShop/apps/orderApp/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.views import View
from .shop_cart import shopCart
from apps.productApp.models import Product
from django.http import HttpResponse
from apps.accountsApp.models import Customer
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Order,OrderDetail,Payment
from .forms import OrderForm
from django.core.exceptions import ObjectDoesNotExist
from apps.discountsApp.forms import CouponForm
from django.db.models import Q
from apps.discountsApp.models import Coupons
from datetime import datetime
from django.contrib import messages
import utils
#----------------------------------------------------------------------------------

class shopCartView(View):
    def get(self, request,*args, **kwargs):
        shop_cart=shopCart(request)
        return render(request, 'order_app/order.html',{'shop_cart':shop_cart})
  
  
  
### for reload after delete from shop cart   
def show_shop_cart(request):
        shop_cart=shopCart(request)
        total_price_detail=shop_cart.calc_total_price()
        final_price,delivery,tax=utils.get_price_delivery_tax(total_price_detail)
        context={
            'shop_cart':shop_cart,
            'shop_cart_count':shop_cart.count,
            'total_price_detail':total_price_detail,
            'delivery':delivery, 
            'tax':tax,
            'final_price':final_price
        }
        return render(request, 'order_app/partials/show_shop_cart.html',context)     
    
    
    
def add_to_shop_cart(request):
    product_id=request.GET.get('product_id')
    qty=request.GET.get('qty')
    shop_cart=shopCart(request)
    product=get_object_or_404(Product,id=product_id)
    shop_cart.add_to_shop_cart(product,qty)
    return HttpResponse(shop_cart.count)
        
        
        
def delete_from_shop_cart(request):
    product_id=request.GET.get('product_id')        
    shop_cart=shopCart(request)
    product=get_object_or_404(Product,id=product_id)
    shop_cart.delete_from_shop_cart(product)
    return redirect('orders:show_shop_cart')   


def update_shop_cart(request):
    product_id_list=request.GET.getlist('product_id_list[]')
    qty_list=request.GET.getlist('qty_list[]')
    shop_cart=shopCart(request)
    shop_cart.update_shop_cart(product_id_list,qty_list)
    return redirect('orders:show_shop_cart')


def status_of_shop_cart(request):
    shop_cart=shopCart(request)
    return HttpResponse(shop_cart.count)   



#------------------------------------------------------------------------------------------------

class CreateOrderView(LoginRequiredMixin,View):
    def get(self, request):
        try:
            customer=Customer.objects.get(user=request.user)
        except ObjectDoesNotExist:
            customer=Customer.objects.create(user=request.user)  
                    
        order=Order.objects.create(customer=customer,payment=get_object_or_404(Payment,id=1))    
        
        shop_cart=shopCart(request)
        for item in shop_cart:
            OrderDetail.objects.create(
                order=order,
                product=item['product'],
                price=item['price'],
                qty=item['qty']

            )
        return redirect('orders:checkout_order',order.id) 
       
#------------------------------------------------------------------------------------------------

class CheckoutOrderView(LoginRequiredMixin,View):
    def get(self,request,order_id):
        user=request.user
        customer=get_object_or_404(Customer,user=user)
        order=get_object_or_404(Order,id=order_id)
        shop_cart=shopCart(request)
        
        total_price_detail=shop_cart.calc_total_price()
        final_price,delivery,tax=utils.get_price_delivery_tax(total_price_detail,order.discount)
        
        data_form={
            "name":user.name,
            "family":user.family,
            "email":user.email,
            "phone_number":customer.phone_number,
            "address":customer.address,
            
        }

        form=OrderForm(data_form)
        form_coupon=CouponForm()
        context={
            'shop_cart':shop_cart,
            'total_price_detail':total_price_detail,
            'delivery':delivery,
            'tax':tax,
            'final_price':final_price,
            'order':order,
            'form':form,    
            'form_coupon':form_coupon
        }
        return render(request,'order_app/checkout.html',context)
    
    
    
    def post(self,request,order_id):
        form=OrderForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
           
            try:
                order=Order.objects.get(id=order_id)
                order.description=data['description']
                order.payment=Payment.objects.get(id=data['payment'])
                order.save()
                
                user=request.user
                user.name=data['name']
                user.family=data['family']
                user.email=data['email']
                user.save()
                
                customer=Customer.objects.get(user=user)
                customer.phone_number=data['phone_number']
                customer.address=data['address']
                customer.save()
                
                messages.success(request,'اطلاعات با موفقیت ثبت شد','success')
                return redirect('payments:zarinpal_payment',order_id)   
              
            except ObjectDoesNotExist:
                messages.error(request,'فاکتوری با این مشخصات یافت نشد.','danger')
                return redirect('orders:checkout_order',order_id)   
           
           
           
           
           
           
               
#------------------------------------------------------------------------------------------------
        
class ApplyCoupon(View):
    def post(self, request, *args, **kwargs):
        order_id=kwargs['order_id']
        form=CouponForm(request.POST)
        if form.is_valid():
            data=form.cleaned_data
            coupon_code=data['coupon_code']
            
            coupon=Coupons.objects.filter(
                Q(coupon_code=coupon_code) &
                Q(is_active=True) &
                Q(start_date__lte=datetime.now()) &
                Q(end_date__gte=datetime.now())
            )
            discount=0
            try:
                order=Order.objects.get(id=order_id)
                if coupon:
                    discount=coupon[0].discount
                    order.discount=discount
                    order.save()
                    messages.success(request,'کد تخفیف اعمال شد','success')
                    return redirect('orders:checkout_order',order_id) 
                else:
                    messages.error(request,'کد تخفیف اعمال نشد','danger')
                    order.discount=discount
                    order.save()
            except ObjectDoesNotExist:
                messages.error(request,'سفارش موجود نیست','danger')
            return redirect('orders:checkout_order',order_id) 
                    

myShop/templates/order_app/partials/show_shop_cart.html
{% load humanize %}
<!-- 
{% if shop_cart_count > 0 %}
    

    
<div class="container mt-4 mb-4">
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>ردیف</th>
                <th>عکس کالا</th>
                <th>نام کالا</th>
                <th>قیمت واحد</th>
                <th>تعداد</th>
                <th>قیمت کل</th>
                <th>#</th>
            </tr>
        </thead>

        
{% for item in shop_cart %}
        <tr>
            <td>{{forloop.counter}}</td>
            <td>
                <img src="{{media_url}}{{item.product.image_name}}" width="100" alt="">
            </td>
            <td>{{item.product.product_name}}</td>
            <td>{{item.price | intcomma}}</td>
            <td>{{item.qty}}</td>
            <td>{{item.total_price | intcomma}}</td>
            <td>
                <a style="cursor: pointer;" onclick="delete_from_shop_cart({{item.product.id}})">
                    <i class="fa fa-trash"></i>
                </a>
            </td>
        </tr>
{% endfor %}
    </table>
</div>

{% else %}

    <div class="container text-center" style="margin-top:50px; margin-bottom:120px;"> 
        <h1 class="text-info">سبد خرید شما خالی است</h1>
    </div>

{% endif %} -->









		<!-- site__body -->
        {% if shop_cart_count > 0 %}
            <div class="site__body">
                <div class="page-header">
                    <div class="page-header__container container">
                        <div class="page-header__breadcrumb">
                            <nav aria-label="breadcrumb">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="index.html">خانه</a>
                                        /
                                    </li>
                                    <li class="breadcrumb-item active" aria-current="page">سبد خرید</li>
                                </ol>
                            </nav>
                        </div>
                        <div class="page-header__title">
                            <h1>سبد خرید</h1></div>
                    </div>
                </div>
                <div class="cart block">
                    <div class="container">
                        <table class="cart__table cart-table ">
                            <thead class="cart-table__head ">
                                <tr class="cart-table__row">
                                    <th class="cart-table__column cart-table__column--image text-center">ردیف</th>
                                    <th class="cart-table__column cart-table__column--product text-center">عکس کالا</th>
                                    <th class="cart-table__column cart-table__column--price text-center">نام کالا</th>
                                    <th class="cart-table__column cart-table__column--quantity text-center">قیمت واحد</th>
                                    <th class="cart-table__column cart-table__column--quantity text-center">بعد از تخفیف</th>
                                    <th class="cart-table__column cart-table__column--quantity text-center">تعداد</th>
                                    <th class="cart-table__column cart-table__column--total text-center">جمع کل</th>
                                    <th class="cart-table__column cart-table__column--remove text-center"></th>
                                </tr>
                            </thead>
                            <tbody class="cart-table__body">
                                {% for item in shop_cart %}
                                    <tr class="cart-table__row">
                                        <td class="cart-table__column cart-table__column--product">{{forloop.counter}}</td>
                                        <td class="cart-table__column cart-table__column--image">
                                            <a href=""><img src="{{media_url}}{{item.product.image_name}}" alt=""></a>
                                        </td>
                                        <td class="cart-table__column cart-table__column--product">
                                            <a href="" class="cart-table__product-name">
                                                {{item.product.product_name}}
                                            </a>
                                        </td>

                                        <td class="cart-table__column cart-table__column--price" data-title="قیمت">
                                            {{item.price | intcomma}} تومان
                                        </td>
                                        <td class="cart-table__column cart-table__column--price" data-title="قیمت">
                                            {{item.discount_price | intcomma}} تومان
                                        </td>
                                        <td class="cart-table__column cart-table__column--quantity" data-title="تعداد">
                                            <div class="input-number">
                                                <input id="qty_{{item.product.id}}" type="number" min="1" value="{{item.qty}}" style="width:60px;">
                                            </div>
                                        </td>
                                        <td class="cart-table__column cart-table__column--total" data-title="جمع کل">{{item.total_price | intcomma}} تومان</td>
                                        <td class="cart-table__column cart-table__column--remove">
                                            <button type="button" class="btn btn-light btn-sm btn-svg-icon" onclick="delete_from_shop_cart({{item.product.id}})">
                                                <i class="fa fa-trash"></i>
                                            </button>
                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                        <div class="cart__actions">
                            <form class="cart__coupon-form">
                                <a class="btn btn-primary cart__update-button" onclick="update_shop_cart()">به روز رسانی سبد</a>
                            </form>

                        </div>
                        <div class="row justify-content-end pt-5">
                            <div class="col-12 col-md-7 col-lg-6 col-xl-5">
                                <div class="card">
                                    <div class="card-body">
                                        <h3 class="card-title">مجموع سبد</h3>
                                        <table class="cart__totals">
                                            <thead class="cart__totals-header">
                                                <tr>
                                                    <th>جمع جزء</th>
                                                    <td>{{total_price_detail | intcomma}} تومان</td>
                                                </tr>
                                            </thead>
                                            <tbody class="cart__totals-body">
                                                <tr>
                                                    <th>حمل و نقل</th>
                                                    
                                                    {% if delivery == 0 %}
                                                        <td>رایگان</td>
                                                    {% else %}
                                                        <td>{{delivery | intcomma}} تومان</td>
                                                    {% endif %}
                                                        
                                                </tr>
                                                <tr>
                                                    <th>مالیات</th>
                                                    <td>{{tax | intcomma}} تومان</td>
                                                </tr>
                                            </tbody>
                                            <tfoot class="cart__totals-footer">
                                                <tr>
                                                    <th>جمع کل</th>
                                                    <td>{{final_price | intcomma}} تومان</td>
                                                </tr>
                                            </tfoot>
                                        </table><a class="btn btn-primary btn-xl btn-block cart__checkout-button" href="{% url 'orders:createorder' %}">ادامه خرید</a></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        {% else %}

            <div class="container text-center" style="margin-top:50px; margin-bottom:120px;"> 
                <h1 class="text-info">سبد خرید شما خالی است</h1>
            </div>

        {% endif %}
		<!-- site__body / end -->