myShop/apps/accountsApp/urls.py
from django.urls import path
from .views import *
#----------------------------------------------------------------

app_name='accounts'

urlpatterns =[
    path('register',RegisterUserView.as_view(),name='register'),
    path('verify',VerifyRegisterViews.as_view(),name='verify'),
    path('login/',LoginUserView.as_view(),name='login'),
    path('logout',LogoutUserView.as_view(),name='logout'),
    path('user_panel',UserPanelView.as_view(),name='user_panel'),
    path('remember_password',RememberPasswordView.as_view(),name='remember_password'),
    path('change_password',ChangePasswordView.as_view(),name='change_password'),
    path('user_panel_last_order',user_panel_last_order,name='user_panel_last_order'),
    path('user_panel_update',UserPanelUpdateView.as_view(),name='user_panel_update'),
    path('user_panel_payment',peyment_history,name='user_panel_payment'),
    path('change_password_up',ChangePasswordUserPanelView.as_view(),name='change_password_up'),
]

myShop/myShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('accounts/',include('apps.accountsApp.urls',namespace='accounts')),
    path('product/',include('apps.productApp.urls',namespace='products')),
    path('order/',include('apps.orderApp.urls',namespace='orders')),
    path('discount/',include('apps.discountsApp.urls',namespace='discounts')),
    path('payments/',include('apps.paymentApp.urls',namespace='payments')),
    path('warehouse/',include('apps.warehouseApp.urls',namespace='warehouse')),
    path('search/',include('apps.searchApp.urls',namespace='search_app')),
    path('csw/',include('apps.comments_scoring_whislistApp.urls',namespace='csws')),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

myShop/templates/csw_app/partials/comments.html
{% load render_partial %}
<div class="product-tabs__pane" id="tab-reviews">
    <div class="reviews-view">
        <div class="reviews-view__list">
            <h3 class="reviews-view__header">دیدگاه های مشتریان</h3>
            <div class="reviews-list">
                <ol class="reviews-list__content">
                    
                    {% for comment in product.comments_product.all %}
                        {% if comment.is_active %}
                            {% if comment.comments_parent == None %}
                                <li class="reviews-list__item">
                                    <div class="review">
                                        <div class="review__avatar">
                                            <img src="{{media_url}}images/avatars/avatar-1.jpg" alt=""></div>
                                        <div class="review__content">
                                            <div class="review__author">{{comment.commenting_user}}</div>

                                            <div class="review__text">{{comment.comment_text}}</div>
                                            <div class="review__date">{{comment.register_date}}</div> 
                                        </div>
                                    </div>
                                    <div>
                                       
                                        {% if user.is_authenticated %}
                                            <div>
                                                <a  class="btn btn-info" id="btn_{{comment.id}}" onclick="showcreatecommentForm( {{product.id}} , {{comment.id}} ,'{{product.slug}}' )">
                                                    پاسخ
                                                </a>
                                            
                                            </div >
                                            <div id="comment_form_{{comment.id}}">

                                            </div>
                                        {% endif %}
                                            
                                    </div>
                                </li>

                            
                                {% for comment_child in comment.comment_child.all %}
                                    {% if comment_child.is_active %}
                                        <li class="reviews-list__item" style="background-color:bisque; width:95%; margin:10px 5%;">
                                            <div class="review">
                                                <div class="review__avatar"><img src="{{media_url}}images/avatars/avatar-1.jpg" alt=""></div>
                                                <div class="review__content">
                                                    <div class="review__author">{{comment_child.commenting_user}}</div>

                                                    <div class="review__text">{{comment_child.comment_text}}</div>
                                                    <div class="review__date">{{comment_child.register_date}}</div> 
                                                </div>
                                            </div>
                                        </li>
                                    {% endif %}
                                {% endfor %}
                            {% else %}    
                            
                            
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                        

                </ol>

            </div>
        </div>


        {% if user.is_authenticated %}
            <h3 class="reviews-view__header">دیدگاه خود را بنویسید</h3>
            <div class="row">
                <div class="col-12 col-lg-9 col-xl-8">
                    {% render_partial 'csws:create_comment' slug=product.slug %}
                </div>
            </div>
        {% else %}
            <h5 class="mt-3">برای ثبت نظر
                <a href="{% url 'accounts:login' %}?next=/product/{{product.slug}}/" class="text-danger">ورود</a>
                یا
                <a href="{% url 'accounts:register' %}?next=/product/{{product.slug}}/" class="text-danger">ثبت نام</a>
                انجام دهید.
            </h5>    


        {% endif %}    


    </div>
</div>

myShop/templates/csw_app/partials/create_comment.html
<form action="{% url 'csws:create_comment' slug=slug %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <label for="review-text">ثبت دیدگاه</label>
        {{form}}
    </div>
    <div class="form-group mb-0">
        <button type="submit" class="btn btn-primary btn-lg">ارسال نظر</button>
    </div>
    
</form>