myShop/apps/productApp/urls.py
from django.urls import path
from .views import *

app_name = 'products'

urlpatterns = [
    path('cheapest_products/',cheapest_products,name='cheapest_products'),
    path('newest_products/',th_newest_products,name='newest_products'),
    path('popular_groups/',popular_groups,name='popular_groups'),
    path('product_detail/<slug:slug>/',ProductDetailView.as_view(),name='product_detail'),
    path('related_product/<slug:slug>/',related_products,name='related_product'),
    path('product_group_all/',product_group_all,name='product_group_all'),
    path('products_ech_group/<slug:slug>/',products_ech_groups.as_view(),name='products_ech_group'),
    path('ajax_admin/',get_filter_value_for_feature,name='filter_value_for_feature'),
    path('filter_get_product_groups/',filter_get_product_groups,name='filter_get_product_groups'),
    path('filter_get_product_brands/<slug:slug>/',filter_get_product_brands,name='filter_get_product_brands'),
    path('filter_get_product_features/<slug:slug>/',filter_get_product_features,name='filter_get_product_features'),
    path('compare_list/',ShowCompareListView.as_view(),name='compare_list'),
    path('compare_table/',compare_table,name='compare_table'),
    path('add_to_compare_list/',add_to_compare_list,name='add_to_compare_list'),
    path('delete_from_compare_list/',DeleteFromCompareList,name='delete_from_compare_list'),
    path('status_of_compare_list/',status_of_compare_list,name='status_of_compare_list'),
   
]

myShop/myShop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('apps.mainApp.urls',namespace='main')),
    path('accounts/',include('apps.accountsApp.urls',namespace='accounts')),
    path('product/',include('apps.productApp.urls',namespace='products')),
    path('order/',include('apps.orderApp.urls',namespace='orders')),
    path('discount/',include('apps.discountsApp.urls',namespace='discounts')),
    path('payments/',include('apps.paymentApp.urls',namespace='payments')),
    path('warehouse/',include('apps.warehouseApp.urls',namespace='warehouse')),
    path('search/',include('apps.searchApp.urls',namespace='search_app')),
    path('csw/',include('apps.comments_scoring_whislistApp.urls',namespace='csws')),
    path('ckeditor',include('ckeditor_uploader.urls')),
    path('tinymce/', include('tinymce.urls')),
    
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


admin.site.site_header='پنل مدیریت فروشگاه'
admin.site.index_title='به پنل مدیریت خوش آمدید'

myShop/templates/partials/product/product_box.html
{% load humanize %}

{% if type == 1 %}

<div class="product-card">
    <div class="product-card__image">
        <a href="{{product.get_absolute_url}}">

            <img src="{{media_url}}{{product.image_name}}" alt="">
        </a>
    </div>
    <div class="product-card__info">
        <div class="product-card__name">
            <a href="{{product.get_absolute_url}}">
                {{product.product_name}}
            </a>
        </div>
    </div>
    <div class="product-card__actions">
        
        <div class="product-card__prices">
            {% if product.get_number_in_warehouse <= 0 %}
                <span class='text-danger'>ناموجود</span>
            {% endif %}
        </div>

        {% if product.get_number_in_warehouse > 0 %}
                {% if product.price > product.get_price_by_discount %}
                    <div class="product-card__prices"><del>{{product.price|intcomma}} تومان</div></del>
                    <div class="product-card__prices text-danger">{{product.get_price_by_discount|intcomma}} تومان</div>
                {% else %}
                    <div class="product-card__prices">{{product.price|intcomma}} تومان</div>
                {% endif %}
        {% endif %}

        <div class="product-card__buttons">
            
            {% if product.get_number_in_warehouse > 0 %}
                <button class="btn btn-primary product-card__addtocart" onclick="add_to_shop_cart({{product.id}},1)"
                    type="button">
                    افزودن به سبد
                </button>
            {% endif %}
                


            {% if user.is_authenticated %}
                {% if product.get_user_favorites %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                        <i class="fa fa-heart" style='color: rgb(255, 9, 9); font-size:18px;'></i>
                    </button>
                {% else %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" onclick="addFavorite({{product.id}})" type="button">
                        <i class="fa fa-heart" id="empty_heart_wishlist_{{product.id}}" style='color: rgb(166, 165, 165); font-size:18px;'></i>
                    </button>
                {% endif %}
            {% endif %}

        </div>
    </div>
</div>

{% elif type == 2 %}

<div class="product-card" style="margin-bottom:30px !important;">
    <div class="product-card__image">
        <a href="{{product.get_absolute_url}}">

            <img src="{{media_url}}{{product.image_name}}" alt="">
        </a>
    </div>
    <div class="product-card__badges-list">
        <div class="product-card__badge product-card__badge--sale">جدید</div>
    </div>
    <div class="product-card__info">
        <div class="product-card__name">
            <a href="{{product.get_absolute_url}}">
                {{product.product_name}}
            </a>
        </div>
    </div>
    <div class="product-card__actions">

        <div class="product-card__prices">
            {% if product.get_number_in_warehouse <= 0 %}
                <span class='text-danger'>ناموجود</span>
            {% endif %}
        </div>

        {% if product.get_number_in_warehouse > 0 %}
                {% if product.price > product.get_price_by_discount %}
                    <div class="product-card__prices"><del>{{product.price|intcomma}} تومان</div></del>
                    <div class="product-card__prices text-danger">{{product.get_price_by_discount|intcomma}} تومان</div>
                {% else %}
                    <div class="product-card__prices">{{product.price|intcomma}} تومان</div>
                {% endif %}
        {% endif %}


        <div class="product-card__buttons">

            {% if product.get_number_in_warehouse > 0 %}
                <button class="btn btn-primary product-card__addtocart" onclick="add_to_shop_cart({{product.id}},1)"
                    type="button">
                    افزودن به سبد
                </button>
            {% endif %}



            {% if user.is_authenticated %}
                {% if product.get_user_favorites %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                        <i class="fa fa-heart" style='color: rgb(255, 9, 9); font-size:18px;'></i>
                    </button>
                {% else %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" onclick="addFavorite({{product.id}})" type="button">
                        <i class="fa fa-heart" id="empty_heart_wishlist_{{product.id}}" style='color: rgb(166, 165, 165); font-size:18px;'></i>
                    </button>
                {% endif %}
            {% endif %}


        </div>
    </div>
</div>


{% elif type == 3 %}

<div class="product-card">
    <div class="product-card__image">
        <a href="{{product.get_absolute_url}}">

            <img src="{{media_url}}{{product.image_name}}" alt="">
        </a>
    </div>
    <div class="product-card__info">
        <div class="product-card__name">
            <a href="{{product.get_absolute_url}}">
                {{product.product_name}}
            </a>
        </div>
    </div>
    <div class="product-card__actions">

        <div class="product-card__prices">
            {% if product.get_number_in_warehouse <= 0 %}
                <span class='text-danger'>ناموجود</span>
            {% endif %}
        </div>

        {% if product.get_number_in_warehouse > 0 %}
                {% if product.price > product.get_price_by_discount %}
                    <div class="product-card__prices"><del>{{product.price|intcomma}} تومان</div></del>
                    <div class="product-card__prices text-danger">{{product.get_price_by_discount|intcomma}} تومان</div>
                {% else %}
                    <div class="product-card__prices">{{product.price|intcomma}} تومان</div>
                {% endif %}
        {% endif %}


        <div class="product-card__buttons">

            {% if product.get_number_in_warehouse > 0 %}
                <button class="btn btn-primary product-card__addtocart" onclick="add_to_shop_cart({{product.id}},1)"
                    type="button">
                    افزودن به سبد
                </button>
            {% endif %}



            {% if user.is_authenticated %}
                {% if product.get_user_favorites %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                        <i class="fa fa-heart" style='color: rgb(255, 9, 9); font-size:18px;'></i>
                    </button>
                {% else %}
                    <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" onclick="addFavorite({{product.id}})" type="button">
                        <i class="fa fa-heart" id="empty_heart_wishlist_{{product.id}}" style='color: rgb(166, 165, 165); font-size:18px;'></i>
                    </button>
                {% endif %}
            {% endif %}


        </div>
    </div>
</div>


{% elif type == 4 %}

<div class="products-list__item">
    <div class="product-card">
        <div class="product-card__badges-list">
            <div class="product-card__badge product-card__badge--new">جدید</div>
        </div>
        <div class="product-card__image">
            <a href="{% url 'products:product_detail' slug=product.slug %}">
                <img src="{{media_url}}{{product.image_name}}" alt="">
            </a>
        </div>
        <div class="product-card__info">
            <div class="product-card__name"><a href="product.html">{{product.product_name}}</a></div>

        </div>
        <div class="product-card__actions">

            <div class="product-card__prices">
                {% if product.get_number_in_warehouse <= 0 %}
                    <span class='text-danger'>ناموجود</span>
                {% endif %}
            </div>
    
            {% if product.get_number_in_warehouse > 0 %}
                    {% if product.price > product.get_price_by_discount %}
                        <div class="product-card__prices"><del>{{product.price|intcomma}} تومان</div></del>
                        <div class="product-card__prices text-danger">{{product.get_price_by_discount|intcomma}} تومان</div>
                    {% else %}
                        <div class="product-card__prices">{{product.price|intcomma}} تومان</div>
                    {% endif %}
            {% endif %}
    
    
            <div class="product-card__buttons">
    
                {% if product.get_number_in_warehouse > 0 %}
                    <button class="btn btn-primary product-card__addtocart" onclick="add_to_shop_cart({{product.id}},1)"
                        type="button">
                        افزودن به سبد
                    </button>
                {% endif %}
    
    
    
                {% if user.is_authenticated %}
                    {% if product.get_user_favorites %}
                        <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                            <i class="fa fa-heart" style='color: rgb(255, 9, 9); font-size:18px;'></i>
                        </button>
                    {% else %}
                        <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" onclick="addFavorite({{product.id}})" type="button">
                            <i class="fa fa-heart" id="empty_heart_wishlist_{{product.id}}" style='color: rgb(166, 165, 165); font-size:18px;'></i>
                        </button>
                    {% endif %}
                {% endif %}
    
    
            </div>
        </div>
    </div>
</div>

{% endif %}

myShop/templates/partials/product/root_group.html
<div class="block-header">
    <h3 class="block-header__title">{{title}}</h3>
    <div class="block-header__divider"></div>

</div>